# Generated by Django 5.1.8 on 2025-05-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_literario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.BooleanField(default=False, verbose_name='Foi útil?')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data do feedback')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot_literario.message')),
            ],
            options={
                'verbose_name': 'Feedback de Conversa',
                'verbose_name_plural': 'Feedbacks de Conversas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pergunta')),
                ('answer', models.TextField(verbose_name='Resposta')),
                ('category', models.CharField(blank=True, default='geral', max_length=100, verbose_name='Categoria')),
                ('source', models.CharField(blank=True, default='manual', max_length=100, verbose_name='Fonte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='Embedding')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Item de Conhecimento',
                'verbose_name_plural': 'Itens de Conhecimento',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['category'], name='chatbot_lit_categor_02586f_idx'), models.Index(fields=['active'], name='chatbot_lit_active_bad13b_idx')],
            },
        ),
    ]
