# Generated by Django 5.1.8 on 2025-07-23 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot_literario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot_literario.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='corrected_by',
            field=models.ForeignKey(blank=True, help_text='Admin que realizou a correção', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_messages', to=settings.AUTH_USER_MODEL, verbose_name='Corrigida por'),
        ),
        migrations.AddField(
            model_name='conversationfeedback',
            name='message',
            field=models.ForeignKey(help_text='A mensagem do chatbot que está recebendo o feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot_literario.message'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='Conversa onde ocorreu o erro (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_literario.conversation', verbose_name='Conversa Relacionada'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='knowledge_item',
            field=models.ForeignKey(blank=True, help_text='Item da KB criado/modificado durante esta sessão', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_literario.knowledgeitem', verbose_name='Item de Conhecimento'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='trainer_user',
            field=models.ForeignKey(blank=True, help_text='Admin que realizou o treinamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Treinador'),
        ),
        migrations.AddIndex(
            model_name='chatanalytics',
            index=models.Index(fields=['timestamp', 'intent'], name='chatbot_lit_timesta_b90719_idx'),
        ),
        migrations.AddIndex(
            model_name='chatanalytics',
            index=models.Index(fields=['user'], name='chatbot_lit_user_id_eb6e22_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['trainer_user', '-created_at'], name='chatbot_lit_trainer_910172_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['training_type', '-created_at'], name='chatbot_lit_trainin_7ad486_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['success', '-created_at'], name='chatbot_lit_success_51dc86_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['-created_at'], name='chatbot_lit_created_62e462_idx'),
        ),
    ]
