# Generated by Django 5.1.8 on 2025-06-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_literario', '0002_conversationfeedback_knowledgeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados de Contexto'),
        ),
    ]
