# Generated by Django 5.1.8 on 2025-08-09 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_literario', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(default='')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Chatbot',
                'verbose_name_plural': 'Configurações do Chatbot',
            },
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(default='')),
                ('key_topics', models.JSONField(blank=True, default=list)),
                ('sentiment', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumo da Conversa',
                'verbose_name_plural': 'Resumos das Conversas',
            },
        ),
        migrations.RemoveField(
            model_name='chatanalytics',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Conversa', 'verbose_name_plural': 'Conversas'},
        ),
        migrations.AlterModelOptions(
            name='conversationfeedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.RemoveIndex(
            model_name='trainingsession',
            name='chatbot_lit_trainer_910172_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingsession',
            name='chatbot_lit_trainin_7ad486_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingsession',
            name='chatbot_lit_success_51dc86_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingsession',
            name='chatbot_lit_created_62e462_idx',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='context_data',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_training_session',
        ),
        migrations.RemoveField(
            model_name='conversationfeedback',
            name='helpful',
        ),
        migrations.RemoveField(
            model_name='conversationfeedback',
            name='message',
        ),
        migrations.RemoveField(
            model_name='conversationfeedback',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='knowledgeitem',
            name='active',
        ),
        migrations.RemoveField(
            model_name='knowledgeitem',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='knowledgeitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='knowledgeitem',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='knowledgeitem',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='knowledgeitem',
            name='question',
        ),
        migrations.RemoveField(
            model_name='knowledgeitem',
            name='source',
        ),
        migrations.RemoveField(
            model_name='message',
            name='corrected_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='corrected_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='corrected_response',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='was_corrected',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='corrected_answer',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='knowledge_item',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='original_answer',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='original_question',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='success',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='trainer_user',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='training_type',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversationfeedback',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot_literario.conversation'),
        ),
        migrations.AddField(
            model_name='conversationfeedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conversationfeedback',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='content',
            field=models.TextField(default='Conteúdo a ser preenchido'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='content_type',
            field=models.CharField(choices=[('book', 'Livro'), ('author', 'Autor'), ('genre', 'Gênero'), ('movement', 'Movimento Literário'), ('analysis', 'Análise'), ('quote', 'Citação'), ('biography', 'Biografia'), ('context', 'Contexto Histórico')], default='book', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='embedding_vector',
            field=models.JSONField(blank=True, help_text='Vetor de embedding para busca semântica', null=True),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags para categorização'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='title',
            field=models.CharField(default='Item de Conhecimento', max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='model_used',
            field=models.CharField(blank=True, help_text='Modelo usado para gerar a resposta', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='response_time',
            field=models.FloatField(blank=True, help_text='Tempo de resposta em segundos', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.CharField(choices=[('ai', 'IA'), ('knowledge_base', 'Base de Conhecimento'), ('hybrid', 'Híbrido')], default='ai', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='token_count',
            field=models.IntegerField(blank=True, help_text='Número de tokens da resposta', null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='accuracy_score',
            field=models.FloatField(blank=True, help_text='Score de acurácia', null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='embeddings_generated',
            field=models.IntegerField(default=0, help_text='Embeddings gerados'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='items_total',
            field=models.IntegerField(default=0, help_text='Total de itens para processar'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='items_trained',
            field=models.IntegerField(default=0, help_text='Número de itens processados'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='log_data',
            field=models.JSONField(blank=True, default=dict, help_text='Logs do treinamento'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='name',
            field=models.CharField(default='Sessão de Treinamento', help_text='Nome da sessão de treinamento', max_length=200),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Tempo de processamento em segundos', null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='Nova Conversa', max_length=200),
        ),
        migrations.AlterField(
            model_name='conversationfeedback',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Mensagem de erro se houver'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['content_type', 'is_active'], name='chatbot_lit_content_7d8594_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['created_at'], name='chatbot_lit_created_833e41_idx'),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='chatbot_literario.conversation'),
        ),
        migrations.DeleteModel(
            name='ChatAnalytics',
        ),
    ]
