# Generated by Django 5.1.8 on 2025-06-23 14:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_literario', '0003_conversation_context_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='ID da sessão para agrupar interações de um mesmo usuário anônimo.', max_length=100)),
                ('intent', models.CharField(db_index=True, help_text="Intenção detectada pelo chatbot (ex: 'search', 'recommendation').", max_length=100)),
                ('response_time', models.FloatField(help_text='Tempo de resposta do chatbot em segundos.')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da interação.')),
            ],
            options={
                'verbose_name': 'Análise do Chat',
                'verbose_name_plural': 'Análises do Chat',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Conversa do Chatbot', 'verbose_name_plural': 'Conversas do Chatbot'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Mensagem do Chatbot', 'verbose_name_plural': 'Mensagens do Chatbot'},
        ),
        migrations.RemoveIndex(
            model_name='knowledgeitem',
            name='chatbot_lit_categor_02586f_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgeitem',
            name='chatbot_lit_active_bad13b_idx',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, help_text='Armazena o contexto da conversa, se necessário.'),
        ),
        migrations.AlterField(
            model_name='conversationfeedback',
            name='comment',
            field=models.TextField(blank=True, help_text='Comentário opcional do usuário.', null=True, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='conversationfeedback',
            name='helpful',
            field=models.BooleanField(default=True, help_text='Indica se o usuário considerou a resposta útil.', verbose_name='Foi útil?'),
        ),
        migrations.AlterField(
            model_name='conversationfeedback',
            name='message',
            field=models.ForeignKey(help_text='A mensagem do chatbot que está recebendo o feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot_literario.message'),
        ),
        migrations.AlterField(
            model_name='conversationfeedback',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Feedback'),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o item de conhecimento está ativo e pode ser usado.'),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='answer',
            field=models.TextField(help_text='A resposta que o chatbot deve fornecer.'),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='category',
            field=models.CharField(db_index=True, default='general', help_text="Categoria do conhecimento (ex: 'saudação', 'preços', 'autores').", max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vetor de embedding para a busca semântica.', null=True),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='question',
            field=models.TextField(help_text='A pergunta ou padrão de consulta do usuário.', unique=True),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='source',
            field=models.CharField(blank=True, help_text="Origem da informação (ex: 'manual', 'learned_from_chat').", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatanalytics',
            index=models.Index(fields=['timestamp', 'intent'], name='chatbot_lit_timesta_b90719_idx'),
        ),
        migrations.AddIndex(
            model_name='chatanalytics',
            index=models.Index(fields=['user'], name='chatbot_lit_user_id_eb6e22_idx'),
        ),
    ]
