# Generated by Django 5.1.8 on 2025-08-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_literario', '0003_chatbotconfiguration_conversationsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='active',
            field=models.BooleanField(default=True, help_text='Item ativo na base de conhecimento'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='answer',
            field=models.TextField(default='Conteúdo a ser preenchido', help_text='Resposta ou conteúdo detalhado'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='category',
            field=models.CharField(choices=[('book', 'Livro'), ('author', 'Autor'), ('genre', 'Gênero'), ('movement', 'Movimento Literário'), ('analysis', 'Análise'), ('quote', 'Citação'), ('biography', 'Biografia'), ('context', 'Contexto Histórico'), ('geral', 'Geral')], default='geral', help_text='Categoria do conhecimento', max_length=50),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='confidence',
            field=models.FloatField(default=1.0, help_text='Nível de confiança (0.0 a 1.0)'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vetor de embedding para busca semântica', null=True),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='question',
            field=models.CharField(db_index=True, default='Tópico a ser definido', help_text='Pergunta ou tópico principal', max_length=500),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='source',
            field=models.CharField(blank=True, default='knowledge_base', help_text='Fonte da informação', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='content',
            field=models.TextField(blank=True, help_text='Conteúdo adicional (compatibilidade)'),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='content_type',
            field=models.CharField(choices=[('book', 'Livro'), ('author', 'Autor'), ('genre', 'Gênero'), ('movement', 'Movimento Literário'), ('analysis', 'Análise'), ('quote', 'Citação'), ('biography', 'Biografia'), ('context', 'Contexto Histórico'), ('geral', 'Geral')], default='book', help_text='Tipo de conteúdo (compatibilidade)', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='embedding_vector',
            field=models.JSONField(blank=True, help_text='Vetor de embedding alternativo (compatibilidade)', null=True),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados adicionais'),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='title',
            field=models.CharField(blank=True, help_text='Título alternativo (compatibilidade)', max_length=200),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['category', 'active'], name='chatbot_lit_categor_434ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['question'], name='chatbot_lit_questio_205d39_idx'),
        ),
    ]
