# Generated by Django 5.1.8 on 2025-07-01 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_literario', '0005_add_training_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='confidence',
            field=models.FloatField(default=0.8, help_text='Nível de confiança na exatidão da resposta (0.0 a 1.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
