# Generated by Django 5.1.8 on 2025-07-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
    ]
