# Generated by Django 5.1.8 on 2025-07-23 21:20

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='users', variations={'thumbnail': {'crop': True, 'height': 100, 'width': 100}}, verbose_name='Foto'),
        ),
    ]
