# Generated by Django 5.1.8 on 2025-07-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
    ]
