# Generated by Django 5.1.4 on 2025-01-16 12:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('capa', models.ImageField(default='livros/capas/default.jpg', upload_to='livros/capas/', verbose_name='Capa')),
                ('editora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Editora')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('classificacao', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Classificação')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'cgbookstore_book',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='UserBookShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_type', models.CharField(choices=[('favorito', 'Favorito'), ('lendo', 'Lendo'), ('vou_ler', 'Vou Ler'), ('lido', 'Lido')], max_length=20, verbose_name='Tipo de Prateleira')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('personal_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação Pessoal')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='core.book', verbose_name='Livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelf', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Estante do Usuário',
                'verbose_name_plural': 'Estantes dos Usuários',
                'db_table': 'cgbookstore_bookshelf',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'book', 'shelf_type')},
            },
        ),
    ]
