# Generated by Django 5.1.8 on 2025-07-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsection',
            name='config_json',
            field=models.JSONField(blank=True, help_text='Configurações específicas em formato JSON para este layout.', null=True, verbose_name='Configurações Adicionais (JSON)'),
        ),
    ]
