# Generated by Django 5.1.8 on 2025-07-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customsection_config_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultshelftype',
            name='filtro_campo',
            field=models.CharField(choices=[('categoria__icontains', 'Categoria (contém)'), ('genero__icontains', 'Gênero (contém)'), ('autor__icontains', 'Autor (contém)'), ('titulo__icontains', 'Título (contém)'), ('temas__icontains', 'Temas (contém)'), ('e_lancamento', 'É Lançamento (True)'), ('e_destaque', 'É Destaque (True)'), ('adaptado_filme', 'Adaptado para Filme (True)'), ('e_manga', 'É Mangá (True)')], help_text='Selecione o campo do livro para filtrar.', max_length=50, verbose_name='Campo do Filtro'),
        ),
        migrations.AlterField(
            model_name='defaultshelftype',
            name='filtro_valor',
            field=models.CharField(blank=True, help_text="O texto a ser procurado. Deixe em branco para campos como 'É Lançamento'.", max_length=50, verbose_name='Valor do Filtro'),
        ),
    ]
