# Generated by Django 5.1.4 on 2025-01-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_userbookshelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
