# Generated by Django 5.1.8 on 2025-07-29 11:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_defaultshelftype_filtro_campo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelfsection',
            name='livros',
        ),
        migrations.RemoveField(
            model_name='bookshelfsection',
            name='section',
        ),
        migrations.RemoveField(
            model_name='bookshelfsection',
            name='shelf_type',
        ),
        migrations.AlterModelOptions(
            name='homesection',
            options={'ordering': ['ordem', 'titulo'], 'verbose_name': 'Seção da Home', 'verbose_name_plural': 'Seções da Home'},
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='descricao',
        ),
        migrations.AddField(
            model_name='homesection',
            name='customization_options',
            field=models.JSONField(blank=True, help_text='Configurações avançadas como cores, transparência, formato de cards, etc.', null=True, verbose_name='Opções de Personalização (JSON)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='max_books',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Máximo de Livros'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='shelf_behavior',
            field=models.CharField(blank=True, choices=[('manual', 'Seleção Manual de Livros'), ('automatic', 'Filtro Automático')], help_text='Escolha como os livros desta prateleira serão selecionados.', max_length=20, verbose_name='Tipo de Prateleira'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='shelf_filter_field',
            field=models.CharField(blank=True, choices=[('e_lancamento', 'É Lançamento'), ('e_destaque', 'É Destaque'), ('bestsellers', 'Mais Vendidos (por quantidade vendida)'), ('most_viewed', 'Mais Acessados (por quantidade de acessos)'), ('adaptado_filme', 'Adaptado para Filme/Série'), ('e_manga', 'É Mangá'), ('categoria__icontains', 'Categoria (contém texto)'), ('autor__icontains', 'Autor (contém texto)'), ('titulo__icontains', 'Título (contém texto)')], help_text="Usado apenas se o tipo for 'Filtro Automático'.", max_length=50, verbose_name='Filtro Automático'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='shelf_filter_value',
            field=models.CharField(blank=True, help_text="Ex: 'Ficção Científica' para o filtro de Categoria.", max_length=100, verbose_name='Valor para o Filtro'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='css_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='Classe CSS Adicional'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='tipo',
            field=models.CharField(choices=[('shelf', 'Prateleira de Livros'), ('video', 'Seção de Vídeos'), ('author', 'Seção de Autores'), ('ad', 'Área de Propaganda'), ('link_grid', 'Grade de Links'), ('banner', 'Banner Personalizado'), ('custom', 'Seção Genérica'), ('background', 'Imagem de Fundo do Site')], max_length=20, verbose_name='Tipo de Seção'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título da Seção'),
        ),
        migrations.CreateModel(
            name='HomeSectionBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homesection')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('section', 'book')},
            },
        ),
        migrations.AddField(
            model_name='homesection',
            name='manual_books',
            field=models.ManyToManyField(blank=True, related_name='home_sections', through='core.HomeSectionBookItem', to='core.book', verbose_name='Livros Manuais'),
        ),
        migrations.DeleteModel(
            name='BookShelfItem',
        ),
        migrations.DeleteModel(
            name='BookShelfSection',
        ),
        migrations.DeleteModel(
            name='DefaultShelfType',
        ),
    ]
