# Generated by Django 5.1.8 on 2025-07-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_bookshelfsection_livros_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'ordering': ['-is_primary', 'id'], 'verbose_name': 'Autor do Livro', 'verbose_name_plural': 'Autores dos Livros'},
        ),
    ]
