# Generated by Django 5.1.8 on 2025-07-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bookauthor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o livro está disponível no site.', verbose_name='Ativo'),
        ),
    ]
