# Generated by Django 5.1.4 on 2025-01-22 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_update_bookshelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='book',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='userbookshelf',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='userbookshelf',
            name='personal_rating',
        ),
        migrations.AlterField(
            model_name='book',
            name='autor',
            field=models.CharField(max_length=200, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='livros/capas/', verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='book',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='book',
            name='editora',
            field=models.CharField(blank=True, max_length=100, verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='userbookshelf',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='core.book'),
        ),
        migrations.AlterField(
            model_name='userbookshelf',
            name='shelf_type',
            field=models.CharField(choices=[('favorito', 'Favorito'), ('lendo', 'Lendo'), ('vou_ler', 'Quero Ler'), ('lido', 'Lido')], max_length=20, verbose_name='Tipo de Prateleira'),
        ),
        migrations.AlterField(
            model_name='userbookshelf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userbookshelf',
            table=None,
        ),
    ]
