# Generated by Django 5.1.4 on 2025-01-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_book_classificacao_remove_book_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='capa',
            field=models.ImageField(blank=True, default='livros/capas/default.jpg', null=True, upload_to='livros/capas/', verbose_name='Capa'),
        ),
    ]
