# Generated by Django 5.1.8 on 2025-08-01 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_book_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsection',
            name='section',
            field=models.OneToOneField(limit_choices_to={'tipo': 'author'}, on_delete=django.db.models.deletion.CASCADE, related_name='author_section', to='core.homesection', verbose_name='Seção'),
        ),
    ]
