# Generated by Django 5.1.4 on 2025-01-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_book_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='livros/capas/', verbose_name='Capa'),
        ),
    ]
