# Generated by Django 5.1.8 on 2025-08-05 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_authorsection_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_books', to=settings.AUTH_USER_MODEL, verbose_name='Sugerido por'),
        ),
        migrations.AddField(
            model_name='book',
            name='visibility',
            field=models.CharField(choices=[('public', 'Público (Aprovado)'), ('private', 'Privado (Aguardando Revisão)')], db_index=True, default='public', help_text='Público: visível para todos. Privado: apenas para quem adicionou e para admins.', max_length=10, verbose_name='Visibilidade'),
        ),
    ]
