# Generated by Django 5.1.8 on 2025-08-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_book_created_by_book_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitem',
            name='custom_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.customsection', verbose_name='Seção Personalizada'),
        ),
    ]
