# Generated by Django 5.1.4 on 2025-01-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_book_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='adaptacoes',
            field=models.TextField(blank=True, verbose_name='Adaptações'),
        ),
        migrations.AddField(
            model_name='book',
            name='apendices',
            field=models.TextField(blank=True, verbose_name='Apêndices'),
        ),
        migrations.AddField(
            model_name='book',
            name='bibliografia',
            field=models.TextField(blank=True, verbose_name='Bibliografia'),
        ),
        migrations.AddField(
            model_name='book',
            name='citacoes',
            field=models.TextField(blank=True, verbose_name='Citações'),
        ),
        migrations.AddField(
            model_name='book',
            name='classificacao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Classificação Indicativa'),
        ),
        migrations.AddField(
            model_name='book',
            name='colecao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Coleção'),
        ),
        migrations.AddField(
            model_name='book',
            name='curiosidades',
            field=models.TextField(blank=True, verbose_name='Curiosidades'),
        ),
        migrations.AddField(
            model_name='book',
            name='dimensoes',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dimensões'),
        ),
        migrations.AddField(
            model_name='book',
            name='edicao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Edição'),
        ),
        migrations.AddField(
            model_name='book',
            name='enredo',
            field=models.TextField(blank=True, verbose_name='Enredo'),
        ),
        migrations.AddField(
            model_name='book',
            name='formato',
            field=models.CharField(blank=True, max_length=50, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='book',
            name='genero',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gênero Literário'),
        ),
        migrations.AddField(
            model_name='book',
            name='glossario',
            field=models.TextField(blank=True, verbose_name='Glossário'),
        ),
        migrations.AddField(
            model_name='book',
            name='idioma',
            field=models.CharField(blank=True, max_length=50, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='book',
            name='ilustrador',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ilustrador'),
        ),
        migrations.AddField(
            model_name='book',
            name='indice',
            field=models.TextField(blank=True, verbose_name='Índice'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localização na Biblioteca'),
        ),
        migrations.AddField(
            model_name='book',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas de Rodapé'),
        ),
        migrations.AddField(
            model_name='book',
            name='numero_paginas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Páginas'),
        ),
        migrations.AddField(
            model_name='book',
            name='personagens',
            field=models.TextField(blank=True, verbose_name='Personagens Principais'),
        ),
        migrations.AddField(
            model_name='book',
            name='peso',
            field=models.CharField(blank=True, max_length=20, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='book',
            name='posfacio',
            field=models.TextField(blank=True, verbose_name='Posfácio'),
        ),
        migrations.AddField(
            model_name='book',
            name='preco',
            field=models.JSONField(blank=True, default=dict, verbose_name='Preços'),
        ),
        migrations.AddField(
            model_name='book',
            name='prefacio',
            field=models.TextField(blank=True, verbose_name='Prefácio/Introdução'),
        ),
        migrations.AddField(
            model_name='book',
            name='premios',
            field=models.TextField(blank=True, verbose_name='Prêmios'),
        ),
        migrations.AddField(
            model_name='book',
            name='publico_alvo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Público-alvo'),
        ),
        migrations.AddField(
            model_name='book',
            name='redes_sociais',
            field=models.JSONField(blank=True, default=dict, verbose_name='Redes Sociais'),
        ),
        migrations.AddField(
            model_name='book',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='book',
            name='temas',
            field=models.TextField(blank=True, verbose_name='Temas'),
        ),
        migrations.AddField(
            model_name='book',
            name='tradutor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tradutor'),
        ),
        migrations.AddField(
            model_name='book',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
