# Generated by Django 5.1.8 on 2025-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_eventitem_custom_section'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userbookshelf',
            constraint=models.UniqueConstraint(condition=models.Q(('shelf_type', 'favorito'), _negated=True), fields=('user', 'book', 'shelf_type'), name='unique_user_book_non_favorite'),
        ),
    ]
