# Generated by Django 5.1.4 on 2025-01-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_book_adaptacoes_book_apendices_book_bibliografia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='capa_preview',
            field=models.ImageField(blank=True, null=True, upload_to='livros/capas/previews/', verbose_name='Preview da Capa'),
        ),
    ]
