# Generated by Django 5.1.8 on 2025-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userbookshelf_unique_user_book_non_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avaliacao_media',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Avaliação média do livro (de 0 a 5), preenchida manualmente.', max_digits=3, null=True, verbose_name='Avaliação Média'),
        ),
    ]
