# Generated by Django 5.1.4 on 2025-01-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_book_capa_preview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbookshelf',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_style',
            field=models.JSONField(blank=True, default={'background_color': '#ffffff', 'border_color': '#dee2e6', 'border_radius': '0.5rem', 'hover_effect': 'translate', 'icon_style': 'default', 'image_style': 'circle', 'text_color': '#000000'}),
        ),
    ]
