# Generated by Django 5.1.4 on 2025-01-28 12:38

import cgbookstore.apps.core.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_userbookshelf_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_style',
            field=models.JSONField(blank=True, default=cgbookstore.apps.core.models.profile.Profile.default_card_style),
        ),
    ]
