# Generated by Django 5.1.8 on 2025-09-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_book_avaliacao_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='role',
            field=models.CharField(blank=True, help_text='Ex: Autor principal, Co-autor, etc.', max_length=100, verbose_name='Função'),
        ),
    ]
