# Generated by Django 5.1.4 on 2025-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_profile_card_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='banners/', verbose_name='Imagem')),
                ('imagem_mobile', models.ImageField(blank=True, null=True, upload_to='banners/mobile/', verbose_name='Imagem Mobile')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Link')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de fim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['ordem', '-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='adaptado_filme',
            field=models.BooleanField(default=False, verbose_name='Adaptado para filme/série'),
        ),
        migrations.AddField(
            model_name='book',
            name='e_destaque',
            field=models.BooleanField(default=False, verbose_name='Em destaque'),
        ),
        migrations.AddField(
            model_name='book',
            name='e_lancamento',
            field=models.BooleanField(default=False, verbose_name='É lançamento'),
        ),
        migrations.AddField(
            model_name='book',
            name='e_manga',
            field=models.BooleanField(default=False, verbose_name='É manga'),
        ),
        migrations.AddField(
            model_name='book',
            name='ordem_exibicao',
            field=models.IntegerField(default=0, verbose_name='Ordem de exibição'),
        ),
        migrations.AddField(
            model_name='book',
            name='quantidade_acessos',
            field=models.IntegerField(default=0, verbose_name='Quantidade de acessos'),
        ),
        migrations.AddField(
            model_name='book',
            name='quantidade_vendida',
            field=models.IntegerField(default=0, verbose_name='Quantidade vendida'),
        ),
        migrations.AddField(
            model_name='book',
            name='tipo_shelf_especial',
            field=models.CharField(blank=True, choices=[('lancamentos', 'Lançamentos'), ('mais_vendidos', 'Mais Vendidos'), ('mais_acessados', 'Mais Acessados'), ('destaques', 'Destaques'), ('filmes', 'Adaptados para Filme/Série'), ('mangas', 'Mangás')], max_length=50, verbose_name='Tipo de prateleira especial'),
        ),
    ]
