# Generated by Django 5.1.4 on 2025-01-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_banner_book_adaptado_filme_book_e_destaque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Promocional'),
        ),
    ]
