# Generated by Django 5.1.4 on 2025-02-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_recommendation_interaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recommendationinteraction',
            new_name='core_recomm_user_id_019362_idx',
            old_name='core_recomm_user_id_0c7d6c_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationinteraction',
            new_name='core_recomm_interac_c82d3c_idx',
            old_name='core_recomm_interac_99e969_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationinteraction',
            new_name='core_recomm_source_d994f9_idx',
            old_name='core_recomm_source_dd8b20_idx',
        ),
    ]
