# Generated by Django 5.1.4 on 2025-02-10 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_homesection_bookshelfitem_bookshelfsection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Propaganda', 'verbose_name_plural': 'Propagandas'},
        ),
        migrations.AlterModelOptions(
            name='bookshelfitem',
            options={'ordering': ['ordem', '-added_at'], 'verbose_name': 'Item da Prateleira', 'verbose_name_plural': 'Itens da Prateleira'},
        ),
        migrations.AlterModelOptions(
            name='bookshelfsection',
            options={'verbose_name': 'Prateleira de Livros', 'verbose_name_plural': 'Prateleiras de Livros'},
        ),
        migrations.AlterModelOptions(
            name='linkgriditem',
            options={'ordering': ['ordem'], 'verbose_name': 'Item da Grade de Links', 'verbose_name_plural': 'Itens da Grade de Links'},
        ),
        migrations.AlterModelOptions(
            name='videosection',
            options={'verbose_name': 'Seção de Vídeo', 'verbose_name_plural': 'Seções de Vídeo'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='section',
            field=models.OneToOneField(limit_choices_to={'tipo': 'ad'}, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='core.homesection', verbose_name='Seção'),
        ),
        migrations.AlterField(
            model_name='bookshelfitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em'),
        ),
        migrations.AlterField(
            model_name='bookshelfitem',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book', verbose_name='Livro'),
        ),
        migrations.AlterField(
            model_name='bookshelfitem',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bookshelfsection', verbose_name='Prateleira'),
        ),
        migrations.AlterField(
            model_name='bookshelfsection',
            name='section',
            field=models.OneToOneField(limit_choices_to={'tipo': 'shelf'}, on_delete=django.db.models.deletion.CASCADE, related_name='book_shelf', to='core.homesection', verbose_name='Seção'),
        ),
        migrations.AlterField(
            model_name='linkgriditem',
            name='section',
            field=models.ForeignKey(limit_choices_to={'tipo': 'link_grid'}, on_delete=django.db.models.deletion.CASCADE, related_name='link_items', to='core.homesection', verbose_name='Seção'),
        ),
        migrations.AlterField(
            model_name='videosection',
            name='section',
            field=models.OneToOneField(limit_choices_to={'tipo': 'video'}, on_delete=django.db.models.deletion.CASCADE, related_name='video_section', to='core.homesection', verbose_name='Seção'),
        ),
    ]
