# Generated by Django 5.1.4 on 2025-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultShelfType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('identificador', models.CharField(max_length=50, unique=True, verbose_name='Identificador')),
                ('filtro_campo', models.CharField(max_length=50, verbose_name='Campo do Filtro')),
                ('filtro_valor', models.CharField(max_length=50, verbose_name='Valor do Filtro')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Prateleira Padrão',
                'verbose_name_plural': 'Tipos de Prateleiras Padrão',
                'ordering': ['ordem'],
            },
        ),
    ]
