# Generated by Django 5.1.4 on 2025-02-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_videoitem_remove_videosection_ordem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosectionitem',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
