# Generated by Django 5.1.4 on 2025-02-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_user_password_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='apendices',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bibliografia',
        ),
        migrations.RemoveField(
            model_name='book',
            name='glossario',
        ),
        migrations.RemoveField(
            model_name='book',
            name='indice',
        ),
        migrations.RemoveField(
            model_name='book',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='book',
            name='posfacio',
        ),
        migrations.RemoveField(
            model_name='book',
            name='prefacio',
        ),
        migrations.AddField(
            model_name='book',
            name='capa_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL da Capa'),
        ),
        migrations.AddField(
            model_name='book',
            name='external_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados Externos'),
        ),
        migrations.AddField(
            model_name='book',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Externo'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_temporary',
            field=models.BooleanField(default=False, verbose_name='É Temporário'),
        ),
        migrations.AddField(
            model_name='book',
            name='origem',
            field=models.CharField(default='local', max_length=50, verbose_name='Origem'),
        ),
    ]
