# Generated by Django 5.1.6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_book_apendices_remove_book_bibliografia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelfsection',
            name='shelf_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.defaultshelftype',
                verbose_name='Tipo de Prateleira Personalizada'
            ),
        ),
        migrations.AlterField(
            model_name='bookshelfsection',
            name='tipo_shelf',
            field=models.CharField(
                blank=True,
                choices=[
                    ('latest', 'Últimos Adicionados'),
                    ('bestsellers', 'Mais Vendidos'),
                    ('most_viewed', 'Mais Acessados'),
                    ('featured', 'Destaques'),
                    ('movies', 'Adaptados para Filme/Série'),
                    ('manga', 'Mangás'),
                    ('custom', 'Personalizada')
                ],
                help_text='Usado apenas para compatibilidade. Preferir o campo "Tipo de Prateleira Personalizada".',
                max_length=20,
                verbose_name='Tipo de Prateleira (Legado)'
            ),
        ),
    ]