# Generated by Django 5.1.6 on 2025-03-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_e_digitais_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='e_digitais',
        ),
    ]
