# Generated by Django 5.1.4 on 2025-03-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_book_e_digitais'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('identificador', models.CharField(max_length=50, unique=True, verbose_name='Identificador')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Seção Personalizada',
                'verbose_name_plural': 'Tipos de Seções Personalizadas',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='tipo_shelf_especial',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de prateleira especial'),
        ),
        migrations.CreateModel(
            name='CustomSectionLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('identificador', models.CharField(max_length=50, unique=True, verbose_name='Identificador')),
                ('template_path', models.CharField(max_length=200, verbose_name='Caminho do Template')),
                ('imagem_preview', models.ImageField(blank=True, upload_to='layouts/', verbose_name='Imagem de Preview')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('section_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='core.customsectiontype', verbose_name='Tipo de Seção')),
            ],
            options={
                'verbose_name': 'Layout de Seção Personalizada',
                'verbose_name_plural': 'Layouts de Seções Personalizadas',
                'ordering': ['section_type', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CustomSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('section', models.OneToOneField(limit_choices_to={'tipo': 'custom'}, on_delete=django.db.models.deletion.CASCADE, related_name='custom_section', to='core.homesection', verbose_name='Seção')),
                ('layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='core.customsectionlayout', verbose_name='Layout')),
                ('section_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sections', to='core.customsectiontype', verbose_name='Tipo de Conteúdo')),
            ],
            options={
                'verbose_name': 'Seção Personalizada',
                'verbose_name_plural': 'Seções Personalizadas',
            },
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('data_evento', models.DateTimeField(verbose_name='Data do Evento')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, upload_to='events/', verbose_name='Imagem')),
                ('url', models.URLField(blank=True, verbose_name='Link para inscrição/detalhes')),
                ('em_destaque', models.BooleanField(default=False, verbose_name='Em Destaque')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('custom_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.customsection', verbose_name='Seção Personalizada')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['ordem', 'data_evento'],
            },
        ),
    ]
