# Generated by Django 5.1.4 on 2025-03-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_book_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='idx_book_shelf_especial',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='idx_book_destaque',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='idx_book_lancamento',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='idx_book_vendas',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='idx_book_acessos',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='idx_book_external',
        ),
    ]
