# Generated by Django 5.1.4 on 2025-03-25 06:29

import cgbookstore.apps.core.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_profile_card_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_style',
            field=models.JSONField(blank=True, default=cgbookstore.apps.core.models.profile.get_default_card_style),
        ),
    ]