# Generated by Django 5.1.6 on 2025-03-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20250325_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsectiontype',
            name='metadados',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
