# Generated by Django 5.1.6 on 2025-04-13 17:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_customsectiontype_metadados_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Anúncio', 'verbose_name_plural': 'Anúncios'},
        ),
        migrations.AlterModelOptions(
            name='bookshelfsection',
            options={'verbose_name': 'Prateleira', 'verbose_name_plural': 'Prateleiras'},
        ),
        migrations.AlterModelOptions(
            name='customsection',
            options={'verbose_name': 'Seção Especial', 'verbose_name_plural': 'Seções Especiais'},
        ),
        migrations.AlterModelOptions(
            name='customsectionlayout',
            options={'ordering': ['section_type', 'nome'], 'verbose_name': 'Layout', 'verbose_name_plural': 'Layouts'},
        ),
        migrations.AlterModelOptions(
            name='customsectiontype',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo Seção', 'verbose_name_plural': 'Tipos Seção'},
        ),
        migrations.AlterModelOptions(
            name='defaultshelftype',
            options={'ordering': ['ordem'], 'verbose_name': 'Prateleira Padrão', 'verbose_name_plural': 'Prateleiras Padrão'},
        ),
        migrations.AlterModelOptions(
            name='homesection',
            options={'ordering': ['ordem', 'titulo'], 'verbose_name': 'Seção', 'verbose_name_plural': 'Seções'},
        ),
        migrations.AlterModelOptions(
            name='linkgriditem',
            options={'ordering': ['ordem'], 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='videosection',
            options={'verbose_name': 'Seção Vídeo', 'verbose_name_plural': 'Seções Vídeo'},
        ),
        migrations.AlterField(
            model_name='book',
            name='tipo_shelf_especial',
            field=models.CharField(blank=True, max_length=50, verbose_name='Prateleira'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='tipo',
            field=models.CharField(choices=[('shelf', 'Prateleira de Livros'), ('video', 'Seção de Vídeos'), ('ad', 'Área de Propaganda'), ('link_grid', 'Grade de Links'), ('banner', 'Banner Personalizado'), ('custom', 'Seção Personalizada'), ('background', 'Imagem de Fundo do Site')], max_length=20, verbose_name='Tipo de Seção'),
        ),
        migrations.CreateModel(
            name='BackgroundSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='backgrounds/', verbose_name='Imagem de Fundo')),
                ('opacidade', models.IntegerField(default=70, help_text='Define a intensidade do esmaecimento nas bordas (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Opacidade do Esmaecimento (%)')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('aplicar_em', models.CharField(choices=[('both', 'Ambos os temas'), ('light', 'Apenas tema claro'), ('dark', 'Apenas tema escuro')], default='both', max_length=20, verbose_name='Aplicar em')),
                ('posicao', models.CharField(choices=[('center', 'Centralizado'), ('top', 'Superior'), ('bottom', 'Inferior')], default='center', max_length=20, verbose_name='Posição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('section', models.OneToOneField(limit_choices_to={'tipo': 'background'}, on_delete=django.db.models.deletion.CASCADE, related_name='background_settings', to='core.homesection', verbose_name='Seção')),
            ],
            options={
                'verbose_name': 'Configuração de Background',
                'verbose_name_plural': 'Configurações de Background',
            },
        ),
    ]
