# Generated by Django 5.1.6 on 2025-05-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_readingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='last_read_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
