# Generated by Django 5.1.6 on 2025-05-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_readingprogress_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_quote',
            field=models.TextField(blank=True, max_length=500, verbose_name='Citação Favorita'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_quote_author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Autor da Citação'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_quote_source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fonte da Citação'),
        ),
    ]
