# Generated by Django 5.1.4 on 2025-02-04 10:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_delete_recommendationinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Visualização'), ('click', 'Clique'), ('add_shelf', 'Adicionado à Prateleira'), ('purchase', 'Compra'), ('ignore', 'Ignorado')], max_length=20)),
                ('source', models.CharField(choices=[('general', 'Recomendações Gerais'), ('history', 'Baseado no Histórico'), ('category', 'Baseado em Categoria'), ('similarity', 'Similaridade')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recommendation_score', models.FloatField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_interactions', to='core.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_r_user_id_99fba4_idx'), models.Index(fields=['interaction_type'], name='analytics_r_interac_f0eea9_idx'), models.Index(fields=['source'], name='analytics_r_source_eceee3_idx')],
            },
        ),
    ]
